#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidAppV2.Resource", IsApplication=true)]

namespace AndroidAppV2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::AndroidAppV2.Resource.Attribute.actionBarSize;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bottom_Left_Reservation = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Bottom_Right_Events = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Top_Left_Games = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Top_Right_Menu = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int button1 = 2131099648;
			
			// aapt resource value: 0x7f060016
			public const int button2 = 2131099670;
			
			// aapt resource value: 0x7f060013
			public const int centerImageButton1 = 2131099667;
			
			// aapt resource value: 0x7f060009
			public const int difficultyButton = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int drinkButton = 2131099653;
			
			// aapt resource value: 0x7f060012
			public const int eventButton = 2131099666;
			
			// aapt resource value: 0x7f060004
			public const int foodButton = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int foodmenuButton = 2131099663;
			
			// aapt resource value: 0x7f060001
			public const int frameLayout1 = 2131099649;
			
			// aapt resource value: 0x7f06000e
			public const int gameButton = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int gameListView = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int gametimeButton = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int listView1 = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int miscButton = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int playerButton = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int relativeLayout1 = 2131099660;
			
			// aapt resource value: 0x7f060011
			public const int reservationButton = 2131099665;
			
			// aapt resource value: 0x7f06000d
			public const int tableLayout1 = 2131099661;
			
			// aapt resource value: 0x7f060003
			public const int tableRow1 = 2131099651;
			
			// aapt resource value: 0x7f060010
			public const int tableRow2 = 2131099664;
			
			// aapt resource value: 0x7f060014
			public const int textView1 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int textView2 = 2131099669;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int contactLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int eventLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int foodmenuLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int GameLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ReservationLayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int button1 = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int difficultyButton = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int drinkButton = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int exit = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int foodButton = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int gametimeButton = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int mapButton = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int miscButton = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int no = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int playerButton = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int yes = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int Theme_NoTitle = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
